apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: iris-classifier
spec:
  predictor:
    containers:
      - name: iris-model
        image: localhost:5000/iris-model:v1
        imagePullPolicy: Always
